
package Cassim2;

import javax.swing.JOptionPane;
import javax.swing.UIManager;



public class StartFrame extends javax.swing.JFrame {

    private boolean solutionIsReady;
    
    public StartFrame() {
        initComponents();
        this.setTitle("Cassim 2");
        solutionIsReady = false;
        this.options = new String[]{"Áno", "Nie"};
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtColumns = new javax.swing.JTextField();
        txtRows = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCreateTable = new javax.swing.JButton();
        btnStartSolution = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        chckBoxEditLastInput = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("stĺpcov:");

        jLabel2.setText("riadkov:");

        btnCreateTable.setText("Vytvor tabuľku");
        btnCreateTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateTableActionPerformed(evt);
            }
        });

        btnStartSolution.setText("Otvor výpočet");
        btnStartSolution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartSolutionActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 90)); // NOI18N
        jLabel3.setText("Cassim 2");

        jLabel4.setText("Prosím o ohlásenie akýchkoľvek chýb na jozef.dzama@gmail.com");

        chckBoxEditLastInput.setText("Uprav posledný vstup");
        chckBoxEditLastInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckBoxEditLastInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(0, 132, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtColumns, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtRows, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCreateTable)
                .addGap(31, 31, 31)
                .addComponent(btnStartSolution)
                .addGap(39, 39, 39))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chckBoxEditLastInput)
                .addGap(160, 160, 160))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStartSolution)
                    .addComponent(jLabel1)
                    .addComponent(txtColumns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtRows, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreateTable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chckBoxEditLastInput)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateTableActionPerformed
        if (chckBoxEditLastInput.isSelected() && ValuesSingleton.INSTANCE.data != null) {
            InputTableDialog inputTableDialog = new InputTableDialog(this, rootPaneCheckingEnabled);
            inputTableDialog.setVisible(true);
            return;
        }
        
        try {
            ValuesSingleton.INSTANCE.columns = Integer.parseInt(txtColumns.getText());
            ValuesSingleton.INSTANCE.rows = Integer.parseInt(txtRows.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Počet riadkov a stĺpcov musia byť celé kladné čísla!", "Chyba", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
        String[][] data = new String [ValuesSingleton.INSTANCE.rows+1][ValuesSingleton.INSTANCE.columns+1];
        for (int i = 0; i <= ValuesSingleton.INSTANCE.rows; i++) {
            for (int j = 0; j <= ValuesSingleton.INSTANCE.columns; j++) {
                data[i][j]="0";
            }
        }
        ValuesSingleton.INSTANCE.data = data;  
        
        String[] porovnania = new String [ValuesSingleton.INSTANCE.rows];
        for (int i = 0; i < ValuesSingleton.INSTANCE.rows; i++) {
            porovnania[i] = " = ";
        }
        ValuesSingleton.INSTANCE.porovnaniasPS = porovnania;
        
        String[] nezapornost = new String[ValuesSingleton.INSTANCE.columns];        
        String[] columnNames = new String[ValuesSingleton.INSTANCE.columns+1];
        for (int i = 0; i < ValuesSingleton.INSTANCE.columns; i++) {
            columnNames[i]="x"+i;
            nezapornost[i]=" >= ";
        }
        columnNames[ValuesSingleton.INSTANCE.columns]="x"+ValuesSingleton.INSTANCE.columns;
        ValuesSingleton.INSTANCE.columnNames = columnNames; //new String [ValuesSingleton.INSTANCE.columns]; 
        ValuesSingleton.INSTANCE.nezapornost = nezapornost;
        
        InputTableDialog inputTableDialog = new InputTableDialog(this, rootPaneCheckingEnabled);
        inputTableDialog.setVisible(true);
        
        solutionIsReady = true;
    }//GEN-LAST:event_btnCreateTableActionPerformed

    private void btnStartSolutionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartSolutionActionPerformed
       
        if (!solutionIsReady) {
            JOptionPane.showMessageDialog(this, "Najprv zadajte vstup!", "Chyba", JOptionPane.ERROR_MESSAGE);
            return;
        }
       
        int potvrdenie = JOptionPane.showOptionDialog(this, "Chcete ukladať riešenie tejto úlohy?",
                    "Ukladať?", 0, JOptionPane.WARNING_MESSAGE, null, options, options[1]);
        if (potvrdenie == JOptionPane.YES_OPTION) {
            
        }
        
        ValuesSingleton.INSTANCE.onlyOnce = true; 
        
        ValuesSingleton.INSTANCE.rows = ValuesSingleton.INSTANCE.tableData.length-1;
        ValuesSingleton.INSTANCE.columns = ValuesSingleton.INSTANCE.tableData[0].length-1;
        if (ValuesSingleton.INSTANCE.columnNames.length!=ValuesSingleton.INSTANCE.columns+1) {
            String[] columnNames = new String[ValuesSingleton.INSTANCE.columns+1];
            for (int i = 0; i < ValuesSingleton.INSTANCE.columns; i++) {
                columnNames[i]="x"+i;
            }
            ValuesSingleton.INSTANCE.columnNames = columnNames;
        }
        
        
        SolutionDialog solutionDialog = new SolutionDialog(this, rootPaneCheckingEnabled);
        solutionDialog.setVisible(true); 
        
    }//GEN-LAST:event_btnStartSolutionActionPerformed

    private void chckBoxEditLastInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckBoxEditLastInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chckBoxEditLastInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartFrame().setVisible(true);
            }
        });
    }

    private final String[] options;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateTable;
    private javax.swing.JButton btnStartSolution;
    private javax.swing.JCheckBox chckBoxEditLastInput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtColumns;
    private javax.swing.JTextField txtRows;
    // End of variables declaration//GEN-END:variables
}


